---
title: "DATA VISUALIZATION"
author: "Raikibul Hasan"
date: "2021-12-10"
output: html_document
---

#Contents

-1. [Data overview]


Package Installation
knitr::opts_chunk$set(echo = TRUE, fig.width = 15, fig.height = 5)
```{r}

library(tidyverse)
```

### Here is a data set of soybean. The data set is about Soybean production and use by year and country.

```{r}
soybean_use <-read_delim("data/soybean_use.csv")
summary(soybean_use)
```

### We are going to drop the code column.

```{r}
soybean_use1 <-select(soybean_use,-c("code"))
soybean_use1

```

### We are going to calculate the toatl use of soybean.
```{r}
soybean_use1 %>%
mutate(total=human_food+animal_feed+processed)

```


```{r}
soybean_use1%>%
   filter(entity%in%c("Bangladesh","Luxembourg","Germany","France"))%>%
ggplot(aes(x=year,y=human_food,fill=entity,color=entity)) + 
  geom_line() +  
  labs(title="Year Vs Soybean uses for human food", subtitle=" 4 different countries(Bangladesh,Luxembourg,Germany,France)", y="Soybean uses for human food ", x="year")
```


https://www.kaggle.com/unsdsn/world-happiness?select=2019.csv

https://www.kaggle.com/goyalshalini93/car-data?select=CarPrice_Assignment.csv
```{r}
car <-read_delim("data/Used_Car_Price_Data.csv")
car
```
```{r}
car <-read_delim("data/CarPrice_Assignment.csv")

```
```{r}
car_data<-car %>%
  rename(brandname=car_ID)%>%
  mutate(brandname=word(CarName, 1))
```




```{r}
car_s<-car_data %>%
  mutate(brandname = ifelse(as.character(brandname) == "maxda","mazda",as.character(brandname)))%>%
  mutate(brandname =ifelse(as.character(brandname) == "vokswagen","volkswagen",as.character(brandname)))%>%
  mutate(brandname =ifelse(as.character(brandname) == "toyouta","toyota",as.character(brandname)))%>%
  mutate(brandname =ifelse(as.character(brandname) == "Nissan","nissan",as.character(brandname)))%>%
  mutate(brandname =ifelse(as.character(brandname) == "vw","volkswagen",as.character(brandname)))%>%
  mutate(brandname =ifelse(as.character(brandname) == "porcshce","porsche",as.character(brandname)))
```



```{r}
car_data%>%
ggplot()+
aes(x = carlength,
y = carwidth,
colour = carbody) +
geom_point(aes(shape=fueltype),size=3,alpha=0.7) +  
geom_smooth(method = "lm",formula='y~x',se=FALSE)+ scale_colour_viridis_d()+
labs(x= "Car length (mm)" ,y="Car Width",
     caption="Two different fueltype (GAS & Diesel)",
     title="Car Length VS Car Width ",
     subtitle = "Dimensions for five different car body(Convertible,hardtop,hatchback,sedan,wagon)")+
theme(plot.caption = element_text(face = "italic"))

```
```{r}
car_s
```



```{r}






```

```{r}

car_s %>%
  ggplot()+
      geom_col(aes(x=brandname, y=price,fill=brandname))+
             scale_y_continuous()+
  labs(x="Car Brand Name/Car Company Name",y="Car Price")
```



```{r}
car_s %>%
  mutate(carcompany = fct_lump(brandname, n = 5,w=price)) %>%
  group_by(carcompany,enginetype)%>%
   mutate(carcompany = fct_reorder(carcompany,-price)) %>%
  arrange(desc(price))%>%
  ggplot()+
      geom_col(aes(x=carcompany, y=price,fill=enginetype))+
  scale_y_continuous()+
  labs(x="Reasons",y="Area in hectares")

```


```{r}
pivot_longer(car_s,brandname : price,names_to = "company",values_to = "totalprice")%>%
  ggplot(aes(x=price,color=brandname,fill=car_s))+geom_density(alpha=0.4)+labs(x="[ozone]",
                                                                            title="Garden's densities")+expand_limits(x=c(-5,17))
```

```{r}
car_s %>%
ggplot(aes(x =price ,
fill = carbody,
color = carbody)) +
geom_density(alpha = 0.7)
```

```{r}
car_s%>%
ggplot(aes(x = horsepower, y = highwaympg)) + 
  geom_point(size = 2) + 
  geom_smooth(method = lm, color = 'red4',formula = y~x) + 
  labs(title = 'Relationship between Horsepower and Miles per gallon in cities') + 
  xlab('Horsepower') + 
  ylab('Miles per Gallon') +
  theme_bw() 
```
```{r}
car_s%>%
ggplot()+
aes(x = horsepower,
y = citympg,
colour = fueltype) +
geom_point(aes(shape=fueltype),size=3,alpha=0.7) +  
geom_smooth(method = "lm",formula='y~x',se=FALSE)+ scale_colour_viridis_d()+
labs(x= "Car length (mm)" ,y="Car Width",
     caption="Two different fueltype (GAS & Diesel)",
     title="Car Length VS Car Width ",
     subtitle = "Dimensions for five different car body(Convertible,hardtop,hatchback,sedan,wagon)")+
theme(plot.caption = element_text(face = "italic"))
```

```{r}

count(car_s, aspiration) %>%
ggplot() +
geom_col(aes(x = aspiration, y = n,fill=aspiration))
 

```


```{r}
library(forcats)
car_s %>%
ggplot(aes(y = fct_infreq(cylindernumber),fill=cylindernumber)) +
geom_bar() +

scale_x_continuous(expand = c(0, NA)) +
labs(title = "Palmer penguins species",
y = NULL) +
theme_minimal(14) +
# nice trick from T. Pedersen
theme(panel.ontop = TRUE,
# better to hide the horizontal grid lines
panel.grid.major.y = element_blank())

```

```{r}
ggplot(car_s) +
geom_bar(aes(y = fuelsystem, fill = drivewheel)) +
facet_grid(fct_lump_min(fuelsystem, 4) ~ .,
space = "free", scales = "free_y") +
labs(y = NULL)

```
```{r}
car_s %>%
# define aes here for both geometries
ggplot(aes(y = highwaympg,
x = drivewheel,
fill = fueltype,
# for violin contours and dots
colour = fueltype
)) + # very transparent filling
geom_violin(alpha = 0.1, trim = FALSE) +
geom_point(position = position_jitterdodge(),
alpha = 0.5,
# don't need dots in legend
show.legend = FALSE)

```


